export const paths = {
  login: '/login',
  findHome: '/findHome',
  setHome: '/setHome',
  meets: '/meets',
  meet: '/meet/:id',
  newMeet: '/meets/new',
  requests: '/requests',
  newRequest: '/requests/new',
  request: '/requests/:requestId',
  chats: '/chats',
  homeInfo: '/home',
  homeChats: '/homeChats',
  manage: '/manage',
} as const;

export const routes = [
  { path: paths.login, view: 'login', panel: 'login-main', main: paths.login },
  { path: paths.findHome, view: 'login', panel: 'login-find', main: paths.findHome },
  { path: paths.setHome, view: 'login', panel: 'set-home', main: paths.setHome },
  { path: paths.meets, view: 'meets', panel: 'meets-main', main: paths.meets },
  { path: paths.meet, view: 'meets', panel: 'meet', main: paths.meets },
  { path: paths.newMeet, view: 'meets', panel: 'meets-new', main: paths.meets },
  { path: paths.requests, view: 'requests', panel: 'requests-main', main: paths.requests },
  { path: paths.newRequest, view: 'requests', panel: 'requests-new', main: paths.requests },
  { path: paths.request, view: 'requests', panel: 'request', main: paths.requests },
  { path: paths.chats, view: 'chats', panel: 'chats-user', main: paths.chats },
  { path: paths.homeInfo, view: 'home', panel: 'home-info', main: paths.homeInfo },
  { path: paths.homeChats, view: 'home', panel: 'home-chats', main: paths.homeInfo },
  { path: paths.manage, view: 'manage', panel: 'manage-main', main: paths.manage },
] as const;
